version: '2'
services:
  master:
    build: './master'
    container_name: master
    command: roscore
  
  listener:
    build: './listener'
    container_name: listener
    environment:
      - "ROS_HOSTNAME=listener"
      - "ROS_MASTER_URI=http://master:11311"
    command: roscore

  talker:
    build: './talker'
    container_name: talker
    environment:
      - "ROS_HOSTNAME=listener"
      - "ROS_MASTER_URI=http://master:11311"
    command: tail -f /dev/null
