apiVersion: apps/v1
kind: Deployment
metadata:
  name: rosnode-gp
spec:
  selector:
    matchLabels:
      app: rosnode-gp
  template:
    metadata:
      labels:
        app: rosnode-gp
    spec:
      containers:
      - name: rosnode-gp
        image: gp_navfn_node
        imagePullPolicy: Never
        command: ["/bin/bash", "-c"]
        args:
        - source /root/catkin_ws/devel/setup.bash;
          roslaunch gp_launch gp_navfn_node.launch;
          echo done;
        env:
        - name: ROS_MASTER_URI
          value: http://192.168.9.1:11311
        - name: ROS_IP
          value: 192.168.9.1
      hostNetwork: true
