apiVersion: apps/v1
kind: Deployment
metadata:
  name: remote-gp
spec:
  selector:
    matchLabels:
      app: remote-gp
  template:
    metadata:
      labels:
        app: remote-gp
    spec:
      containers:
      - name: rosnode-alive
        image: gp_navnfn_node
        imagePullPolicy: Never
        command: ["/bin/bash", "-c"]
        args:
        - source /root/catkin_ws/devel/setup.bash;
          rosrun gp_alive alive;
          echo done;
        env:
        - name: ROS_MASTER_URI
          value: http://10.126.20.246:11311
        - name: ROS_HOSTNAME
          value: 10.126.20.246 
        resources:
         #limits:
           #memory: "100Mi"
           #cpu: "500m"

      - name: rosnode-gp
        image: gp_navnfn_node
        imagePullPolicy: Never
        command: ["/bin/bash", "-c"]
        args:
        - source /root/catkin_ws/devel/setup.bash;
          roslaunch gp_launch gp_navfn_node.launch;
          echo done;
        env:
        - name: ROS_MASTER_URI
          value: http://10.126.20.246:11311
        - name: ROS_HOSTNAME
          value: 10.126.20.246
        resources:
         #limits:
           #memory: "100Mi"
           #cpu: "500m"

      hostNetwork: true
